import java.util.ArrayList;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class StartMenu extends javax.swing.JFrame {
	
	// Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton FinishButton;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JComboBox<String> jComboDepartment;
    private javax.swing.JComboBox<String> jComboYear;
    private javax.swing.JComboBox<String> jComboSemester;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel DepartmentLabel;
    private javax.swing.JLabel YearLabel;
    private javax.swing.JLabel SemesterLabel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    //private javax.swing.JTable jTable1;
    // End of variables declaration  
    
    public ArrayList<String> selected_classes = new ArrayList<String>();
    public ArrayList<String> selected_classes_abrv = new ArrayList<String>();
    final DefaultListModel department_list_model = new DefaultListModel();
    private String year, semester;

    /**
     * Creates new form Course_Scheduler_GUI
     */
    public StartMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        //jTable1 = new javax.swing.JTable();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        DepartmentLabel = new javax.swing.JLabel();
        jComboDepartment = new javax.swing.JComboBox<>();
        YearLabel = new javax.swing.JLabel();
        jComboYear = new javax.swing.JComboBox<>();
        SemesterLabel = new javax.swing.JLabel();
        jComboSemester = new javax.swing.JComboBox<>();
        FinishButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        RemoveButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jInternalFrame1.setVisible(true);

        DepartmentLabel.setText("Department:");

        String[] department_strings_lowercase = { "American Studies", "Anthropology", "Art/Art History", "Biology", "Black Studies", "Business Management", "Chemistry", "Chinese", "Computer Science", "Dance", "Economics", "Education", "English Language Learning", "English", "Environmental Science/Studies", "French Studies", "Gender Studies", "German Studies", "Global Perspectives", "History", "Humanities", "Hispanic Studies", "Int'l Literature & Culture", "International Studies", "Mathematics", "Music", "Physical Education", "Philosophy", "Physics", "Political Science", "Psychology", "Sociology", "Theatre"};
        String[] department_strings = { "AMERICAN STUDIES", "ANTHROPOLOGY", "ART/ART HISTORY", "BIOLOGY", "BLACK STUDIES", "BUSINESS MANAGEMENT", "CHEMISTRY", "CHINESE", "COMPUTER SCIENCE", "DANCE", "ECONOMICS", "EDUCATION", "ENGLISH LANGUAGE LEARNING", "ENGLISH", "ENVIRONMENTAL SCIENCE/STUDIES", "FRENCH STUDIES", "GENDER STUDIES", "GERMAN STUDIES", "GLOBAL PERSPECTIVES", "HISTORY", "HUMANITIES", "HISPANIC STUDIES", "INT'L LITERATURE & CULTURE", "INTERNATIONAL STUDIES", "MATHEMATICS", "MUSIC", "PHYSICAL EDUCATION", "PHILOSOPHY", "PHYSICS", "POLITICAL SCIENCE", "PSYCHOLOGY", "SOCIOLOGY", "THEATRE"};
        String[] department_abrv = { "AMS", "ANT", "ART", "BIO", "BLS", "BUS", "CHE", "CHN", "CSI", "DAN", "ECN", "EDU", "ELL", "ENG", "ENV", "FRS", "GEN", "GRS", "GRW", "HIS", "HMN", "HPS", "ILC", "INT", "MAT", "MUS", "PED", "PHL", "PHY", "POL", "PSY", "SOC", "THE" };
        jComboDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(department_strings_lowercase));
        jComboDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //jComboDepartmentActionPerformed(jComboDepartment.getSelectedItem().toString());
            	int index = jComboDepartment.getSelectedIndex();
            	jComboDepartmentActionPerformed(department_strings[index], department_abrv[index], department_strings_lowercase[index]);
            }
        });

        YearLabel.setText("Year:");

        jComboYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"2017", "2018", "2019", "2020"}));
        jComboYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	year = jComboYear.getSelectedItem().toString();
            }
        });

        SemesterLabel.setText("Semester:");

        jComboSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"FALL", "SPRING"}));
        jComboSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	semester = jComboSemester.getSelectedItem().toString();
            }
        });

        FinishButton.setText("Finish");
        FinishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishButtonActionPerformed(evt);
            }
        });

        
        jList1.setModel(department_list_model);
        
        jScrollPane1.setViewportView(jList1);

        RemoveButton.setText("Remove Selected");
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("COURSE SCHEDULER");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FinishButton)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DepartmentLabel)
                                    .addComponent(YearLabel)
                                    .addComponent(SemesterLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(59, 59, 59)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RemoveButton))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DepartmentLabel)
                            .addComponent(jComboDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(YearLabel)
                            .addComponent(jComboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SemesterLabel)
                            .addComponent(jComboSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RemoveButton)
                            .addComponent(FinishButton))))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>   
    
    public String getYearSemester(){
    	return year + semester;
    }
    
    public ArrayList<String> getDepartments(){
		return selected_classes;
	}
    
    public ArrayList<String> getDepartmentCodes(){
    	return selected_classes_abrv;
    }

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	int toRemove = jList1.getSelectedIndex();
    	department_list_model.remove(toRemove);
    	selected_classes.remove(toRemove);
    	selected_classes_abrv.remove(toRemove);
    	System.out.println(selected_classes);
    }                                        

    private void jComboDepartmentActionPerformed(String departmentName, String departmentAbrv, String departmentLowercase) {                                           
        // TODO add your handling code here:
    	if(!selected_classes.contains(departmentName)){
    		selected_classes.add(departmentName);
    		selected_classes_abrv.add(departmentAbrv);
        	department_list_model.addElement(departmentLowercase);
    	}
    	
    	System.out.println(selected_classes);
    	System.out.println(selected_classes_abrv);
    	
    }                                          

    private void FinishButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	//new CalendarUI().setVisible(true);
    	JFrame newFrame = new JFrame();
    	newFrame.setDefaultCloseOperation(EXIT_ON_CLOSE);
    	newFrame.add(new CalendarUI());
    	newFrame.pack();
    	newFrame.setVisible(true);
    }    
    
    public static void openStartMenu(){
    	try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartMenu().setVisible(true);
            }
        });
    }

}
